config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'dogs/index'
  end

  namespace :admin do
    get 'dogs/new'
  end

  namespace :admin do
    get 'dogs/create'
  end

  namespace :admin do
    get 'dogs/show'
  end

  namespace :admin do
    get 'dogs/edit'
  end

  namespace :admin do
    get 'dogs/update'
  end

  namespace :admin do
    get 'dogs/destroy'
  end

  resources :posts
  resources :dashboards
  root 'dashboards#index'  

  resources :posts do
    resources :comments
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Mount API
  mount BuilderApi => '/api'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :photos
    has_many :comments
    accepts_nested_attributes_for :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController
  layout'admin'

  before_action :authenticate_user!
  
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find_by_id(params[:post_id])
    comment = post.comments.create(comment_params)

    redirect_to posts_path
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
    @photo = @post.photos.build
    
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      if params[:photos] != nil
        params[:photos]['avatar'].each do |p|
          @photo = @post.photos.create(avatar: p)
        end
      end
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @photos = @post.photos.all
  end

  private
  def post_params
    params.require(:post).permit(:name, :content, photos_attributes: [:id, :post_id, :avatar])
  end
end

app/helpers/admin/dogs_helper.rb
module Admin::DogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/admin/dogs/create.html.erb
<h1>Admin::Dogs#create</h1>
<p>Find me in app/views/admin/dogs/create.html.erb</p>

app/views/admin/dogs/destroy.html.erb
<h1>Admin::Dogs#destroy</h1>
<p>Find me in app/views/admin/dogs/destroy.html.erb</p>

app/views/admin/dogs/edit.html.erb
<h1>Admin::Dogs#edit</h1>
<p>Find me in app/views/admin/dogs/edit.html.erb</p>

app/views/admin/dogs/index.html.erb
<style>
.card-img-left {
    float: left;
    padding-right: 1em;
    padding-bottom: 1em;
    margin-bottom: -1.25em;
  }

  .btn-circle {
    width: 50px;
    height: 50px;
    text-align: center;
    padding: 10px 0;
    line-height: 1.42;
    border-radius: 35px;
    margin-top: 20px;  
  }
  
  .box-shadow {
    box-shadow: 0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important;    
  }
</style>

<%= link_to '+', new_post_path, class: 'btn btn-outline-info btn-circle box-shadow' %>
</p>

app/views/admin/dogs/new.html.erb
<h1>Admin::Dogs#new</h1>
<p>Find me in app/views/admin/dogs/new.html.erb</p>

app/views/admin/dogs/show.html.erb
<h1>Admin::Dogs#show</h1>
<p>Find me in app/views/admin/dogs/show.html.erb</p>

app/views/admin/dogs/update.html.erb
<h1>Admin::Dogs#update</h1>
<p>Find me in app/views/admin/dogs/update.html.erb</p>

app/views/dashboards/index.html.erb
<div class="bd-example">
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class=""></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2" class=""></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item">
      <div class="card carousel-caption fixed-top" style="width: 15rem; opacity: 0.4; border-radius: 10px; margin-top: 10px; margin-left: 10px; height: 25rem;">
        <div class="card-body">
          <h4 class="card-title">Card title</h4>
          <p class="card-text" style="color: red">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>

      <img class="d-block w-100" alt="First slide [800x400]" src="dog_home_1.jpg" data-holder-rendered="true">
      <div class="carousel-caption d-none d-md-block">
        <h3>First slide label</h3>
        <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
      </div>
    </div>
    <div class="carousel-item active">
      <div class="card carousel-caption fixed-top" style="width: 15rem; opacity: 0.4; border-radius: 10px; margin-top: 10px; margin-left: 10px; height: 25rem;">
        <div class="card-body">
          <h4 class="card-title">Card title</h4>
          <p class="card-text" style="color: red">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>

      <img class="d-block w-100" alt="Second slide [800x400]" src="dog_home_2.jpg" data-holder-rendered="true">
      <div class="carousel-caption d-none d-md-block">
        <h3>Second slide label</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
      </div>
    </div>
    <div class="carousel-item">
      <div class="card carousel-caption fixed-top" style="width: 15rem; opacity: 0.4; border-radius: 10px; margin-top: 10px; margin-left: 10px; height: 25rem;">
        <div class="card-body">
          <h4 class="card-title">Card title</h4>
          <p class="card-text" style="color: red">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
          
      <img class="d-block w-100" alt="Third slide [800x400]" src="dog_home_3.jpg" data-holder-rendered="true">
      <div class="carousel-caption d-none d-md-block">
        <h3>Third slide label</h3>
        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetDog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "shared/nav" %>
  <body>
    <div class="row no-gutters" style="margin-top:100px">
      <div class="col-12 col-sm-6 col-md-4">
        <div class="container"">
          <ul class="nav flex-column">
            <li class="nav-item">
              <%= link_to 'Add Dog', admin_dogs_index_path, class: 'nav-link' %>        
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Feature 1</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Feature 2</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Feature 3</a>
            </li>
          </ul>  
        </div>      
      
      </div>
      <div class="col-6 col-md-8"><%= yield %></div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetDog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "shared/nav" %>    
  <body>
    <div class="container-fluid" style="margin-top:90px">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/index.html.erb
<style>
.card-img-left {
    float: left;
    padding-right: 1em;
    padding-bottom: 1em;
    margin-bottom: -1.25em;
  }

  .btn-circle {
    width: 50px;
    height: 50px;
    text-align: center;
    padding: 10px 0;
    line-height: 1.42;
    border-radius: 35px;
    margin-top: 20px;  
  }
  
  .box-shadow {
    box-shadow: 0 10px 16px 0 rgba(0,0,0,0.2),0 6px 20px 0 rgba(0,0,0,0.19) !important;    
  }
</style>

<script>
function submit_ajax(object, url) {
  var url = '/api/v1/posts/'+url+'/add_like';
    $.ajax(url, {
      type: "POST",
      success: function(response) {
      }
    });
}
</script>

<div class="fixed-top" style="margin-top: 60px; margin-left: 70px">
  <%= link_to '+', new_post_path, class: 'btn btn-outline-info btn-circle box-shadow' %>
</div>

<% @posts.each do |p| %>
    <div class="card border-info mb-3 w-75 mx-auto box-shadow" style="margin-top: 20px">
      <div class="card-header"><%= p.created_at %></div>
      <div class="card-body text-info">
          <%= image_tag p.photos.first.avatar.thumb.url, class: 'card-img-left' %>
      
          <h4 class="card-title">Card title</h4>
          <p class="card-text"><%= p.content %></p>
          <%= link_to "#{p.like}", '', onclick: "submit_ajax(this, #{p.id})", id: "ajax-like-#{p.id}", style: 'color: red' %>
          <i class="icon-heart icons" style="color:red"></i>      
      </div>

      <div class="card-footer text-muted">
        <%= form_with(model: [ p, p.comments.build ]) do |form| %>
          <div class="input-group">
            <%= form.text_field :content, class: 'form-control col col-lg-4', placeholder: 'Comment...' %>
            <span class="input-group-btn">
            <%= button_tag(type: 'submit', class: "btn btn-info") do %>
              <i class="icon-bubbles icons"></i>
             <% end %>
            </span>
          </div>
        <% end %>

        <% p.comments.each do |c| %>
          <div class="form-group">
            <div>
              <%= c.content %>
            </div>
          </div>
        <% end %>         
      </div>

    </div>
<% end %>

app/views/posts/new.html.erb
<div class="card mx-auto" style="max-width: 35rem; margin-top: 30px">
    <div class="card-header">
    Post article
    </div>
    <div class="card-body">
        <%= form_for(@post, html: { multipart: true }) do |f| %>
            <div class="form-group">
                <label>Name</label>
                <div>
                    <%= f.text_field(:name,  { autofocus: true, class: 'form-control', placeholder: 'Name'}) %>
                </div>
            </div>

            <div class="form-group">
                <label>Content</label>
                <div>
                    <%= f.text_area(:content,  { autofocus: true, class: 'form-control'}) %>
                </div>
            </div>

            <div class="form-group">
                <label>Picture</label>
                <div>
                    <%= f.fields_for :photos do |p| %>
                        <div class='field'>
                            <%= p.file_field :avatar, multiple: true, name: "photos[avatar][]" %>
                        </div>
                    <% end %>                    
                </div>
            </div>
        
            <div class='actions'>
            <%= f.submit 'Submit' %>
            </div>                
        <% end %>
    </div>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
<a class="navbar-brand" href="#">
<%= image_tag("logo.png", height: '40', width: '40') %>
Meet Dog
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarColor01">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Post', posts_path, class:'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Admin', admin_dogs_index_path, class: 'nav-link' %>
    </li>
  </ul>
  <form class="form-inline">
    <% if user_signed_in? %>
      <%= link_to('Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger', style: 'margin-right: 40px') %>        
    <% else %>
      <%= link_to('Sign in', new_user_session_path, method: :get, class: 'btn btn-outline-info', style: 'margin-right: 40px') %>        
    <% end %>
    </button>
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>